#upstream backend {
##  server backend:5000;
##   server backend.fcj-namespace:5000;
##kk
#}
#
#server {
#  listen 80;
#  # Any address
#  server_name _;
#
#  root /usr/share/nginx/html;
#  index index.html;
#
#  # Serve the React app
#  location / {
#    try_files $uri $uri/ /index.html;
#  }
#
#  # Proxy API requests to the backend service
#  location /api/ {
#    proxy_pass http://app-loadbalancer-2028228517.ap-southeast-1.elb.amazonaws.com;
#    proxy_http_version 1.1;
#    proxy_set_header Upgrade $http_upgrade;
#    proxy_set_header Connection 'upgrade';
#    proxy_set_header Host $host;
#    proxy_cache_bypass $http_upgrade;
#  }
#
#  # Proxy /uploads requests to backend
#  location /uploads {
#    proxy_pass http://backend;
#  }
#
#  # Health check
#  location /health {
#    return 200 'Healthy';
#    add_header Content-Type text/plain;
#  }
#}

upstream backend {
  server app-loadbalancer-2028228517.ap-southeast-1.elb.amazonaws.com:80;
}

server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /uploads {
    proxy_pass http://backend;  # Giờ đã resolve được qua upstream
  }

  location /health {
    return 200 'Healthy';
    add_header Content-Type text/plain;
  }
}
